#!/usr/bin/env node
/**
 * Regenerates src/generated/schema.ts from the single source of truth,
 * lib/api-v1/openapi.yaml — never hand-edit that generated file. Run
 * `npm run generate` (from sdks/typescript/) any time the spec changes;
 * this is what "reuse the OpenAPI spec, avoid duplication" means in
 * practice for this SDK: request/response/param types are derived, not
 * hand-mirrored from lib/api-v1/dto.ts.
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const specPath = join(__dirname, "..", "..", "..", "lib", "api-v1", "openapi.yaml");
const outPath = join(__dirname, "..", "src", "generated", "schema.ts");

const ast = await openapiTS(new URL(`file://${specPath}`));
const contents = astToString(ast);

const header = `/**
 * AUTO-GENERATED by scripts/generate-types.mjs from lib/api-v1/openapi.yaml.
 * Do not edit by hand — regenerate with \`npm run generate\`.
 */\n`;

await writeFile(outPath, header + contents, "utf8");
console.log(`Wrote ${outPath}`);
