"use strict";

const zapier = require("zapier-platform-core");
const packageJson = require("./package.json");
const { authentication, addApiKeyToHeader } = require("./authentication");

const newAudit = require("./triggers/new_audit");
const newClient = require("./triggers/new_client");
const newReport = require("./triggers/new_report");

const findAudit = require("./searches/find_audit");
const findClient = require("./searches/find_client");
const findReport = require("./searches/find_report");

const createTask = require("./creates/create_task");
const createInteraction = require("./creates/create_interaction");
const updateClient = require("./creates/update_client");

/**
 * The PUBLIC-MAP Zapier app definition — see README.md for the full
 * picture of what this Stage 8 (Zapier sub-stage) scaffold does and does
 * not cover. This file itself is deliberately thin: it only wires
 * together resources generated by scripts/generate-zapier-app.mjs (never
 * hand-edit triggers/, searches/, or creates/ — those are regenerated,
 * not hand-maintained, same discipline as templates/n8n and
 * templates/make) plus the hand-written authentication module.
 */
const App = {
  version: packageJson.version,
  platformVersion: zapier.version,

  authentication,

  // Adds "Authorization: Bearer <apiKey>" to every outgoing request —
  // defined once here (not repeated in every trigger/search/create),
  // the same "never duplicate the auth header logic" principle already
  // applied throughout the n8n/Make/Airtable generators.
  beforeRequest: [addApiKeyToHeader],

  afterResponse: [],

  triggers: {
    [newAudit.key]: newAudit,
    [newClient.key]: newClient,
    [newReport.key]: newReport,
  },

  searches: {
    [findAudit.key]: findAudit,
    [findClient.key]: findClient,
    [findReport.key]: findReport,
  },

  creates: {
    [createTask.key]: createTask,
    [createInteraction.key]: createInteraction,
    [updateClient.key]: updateClient,
  },
};

module.exports = App;
